### PR TITLE
Implementing Accessibility

### PR DESCRIPTION
**Pull request by er-contreras**
- Here we suppose to implement accessibility to our WebSite.
- We work and commit to each of our projects together.

## Summary

- [Page titles](https://www.w3.org/WAI/test-evaluate/preliminary/#title) - We changed the title to "eri8-9"
- [Image text alternatives](https://www.w3.org/WAI/test-evaluate/preliminary/#images) - We add a link to all the icons like in the alt.
- [Text headings](https://www.w3.org/WAI/test-evaluate/preliminary/#headings) - We changed h2 to h1 in John Doe 
- Color contrast - no issues found
 - Resize - no issues found
- Interaction - no issues found
- Moving content - no issues found
- Multimedia - no issues found
- The basic structure of the page - no issues found

### CODE REVIEW

**Review by henatan99 — CHANGES_REQUESTED** [review]
Hi @nidala, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
_Check the comments under the review._

- [x] When I see the basic structure of the page I found two elements/tags in the wrong place. The heading <h2> MY RECENT WORK </h2> is detached from the work-section elements completely. It is a heading for the work-section elements and it should be under the same parent element with the work-section elements. 
- [x] The other is you put `main` tag inside `background-bottom` - `div` element. That violates the correct page structure. `main` tag represents part of the page between the `header` and `footer` sections. 
- [x] You need to have a report summary of the evaluation you have made on your PR. Each summary list should also be linked to the code snippet where file changes are made in the GitHub files.  Please carefully read the [project's requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md), make the necessary changes before you request another review. 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by er-contreras** [comment]
> Hi @Nidala,
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]  When I see the basic structure of the page I found two elements/tags in the wrong place. The heading ##  MY RECENT WORK  is detached from the work-section elements completely. It is a heading for the work-section elements and it should be under the same parent element with the work-section elements.
> * [ ]  The other is you put `main` tag inside `background-bottom` - `div` element. That violates the correct page structure. `main` tag represents part of the page between the `header` and `footer` sections.
> * [ ]  You need to have a report summary of the evaluation you have made on your PR. Each summary list should also be linked to the code snippet where file changes are made in the GitHub files.  Please carefully read the [project's requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md), make the necessary changes before you request another review.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@henatan99 Sorry who is Nidala? are you sure are you reviewing the correct repo?

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ♻️ ⚠️ ⚠️ 🚦 🚦 

Hi @eri8-9 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

star_wars_almost_there

## Aspects to improve (only one) ♻️
_Check the comments under the review._

- [ ] You need to have a report summary of the evaluation you have made on your PR. Each summary list should also be linked to the code snippet where file changes are made in the GitHub files. Please carefully read the project's requirements, make the necessary changes before you request another review.
- What you need to do here is just get better your summary in the PR. For each bullets, you need to have a link where file changes are made in the GitHub files. Do that and you'll be on the other side (the good one). Use [links](https://www.google.com/) like this.
- hint: `[links](https://www.google.com/)`


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi @eri8-9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ayebaishmo — COMMENTED** [review]
So far so good :

The changes are okay and well implamented. Keep it up

**Pull request merged**
